version: 0.2

env:
  secrets-manager:
    KARATE_OPTIONS: KARATE_OPTIONS:KARATE_OPTIONS
    KARATE_ENV: ENV:KARATE_ENV
    TEST_API_URL: APIURL:TEST_API_URL
    CONNECT_TIMEOUT: CONNECT_TIMEOUT:CONNECT_TIMEOUT
    READ_TIMEOUT: KARATE_READTIMEOUT:READ_TIMEOUT
    RETRY_COUNT: KARATE_RETRYCOUNT:RETRY_COUNT
    RETRY_INTERVAL: RETRYINTERVAL:RETRY_INTERVAL
    TEST_USERNAME: username:TEST_USERNAME
    TEST_PASSWORD: password:TEST_PASSWORD
    TEST_URL: DATAINGEST_SERVER_URL:TEST_URL
    TEST_DRIVER_CLASS_NAME: DRIVERCLASSNAME:TEST_DRIVER_CLASS_NAME
    TEST_BOOTSTRAP_SERVERS: KAFKA_SERVER:TEST_BOOTSTRAP_SERVERS
    TEST_GROUP_ID: GROUPID:TEST_GROUP_ID
    TEST_API_USERNAME: API_USERNAME:TEST_API_USERNAME
    TEST_API_PASSWORD: API_PASSWORD:TEST_API_PASSWORD
    TEST_NBS_URL: NBS_URL:TEST_NBS_URL
    TEST_WRONGAPIURL: WRONGAPIURL:TEST_WRONGAPIURL

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y openjdk-17-jdk
      - chmod +x gradlew


  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Karate tests...
      - |
        ./gradlew test \
        -Dkarate.options="$KARATE_OPTIONS" \
        -Dkarate.env="$KARATE_ENV" \
        -Dtest.apiurl="$TEST_API_URL" \
        -DconnectTimeout="$CONNECT_TIMEOUT" \
        -DreadTimeout="$READ_TIMEOUT" \
        -DretryCount="$RETRY_COUNT" \
        -DretryInterval="$RETRY_INTERVAL" \
        -Dtest.username="$TEST_USERNAME" \
        -Dtest.password="$TEST_PASSWORD" \
        -Dtest.url="$TEST_URL" \
        -Dtest.driverClassName="$TEST_DRIVER_CLASS_NAME" \
        -Dtest.bootstrapServers="$TEST_BOOTSTRAP_SERVERS" \
        -Dtest.groupId="$TEST_GROUP_ID" \
        -Dtest.apiusername="$TEST_API_USERNAME" \
        -Dtest.apipassword="$TEST_API_PASSWORD" \
        -Dtest.nbsurl="$TEST_NBS_URL" \
        -Dtest.wrongapiurl="$TEST_WRONGAPIURL"
      
artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: './karatetest/build/cucumber-html-reports/'
  name: karate-cucumberreports.zip

