version: 0.2

env:
  secrets-manager:
    TEST_SECRET: dev/dataingestionteam/karatetest/secrets

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Checking the pre-installed java version && java -version
      - echo Installing dependencies...
      - apt-get update && apt-get install -y jq
      - chmod +x ./karatetest/gradlew

  pre_build:
    commands:
      - TEST_SECRET=$(echo $TEST_SECRET | tr -d '\n' | jq -r)
      - export TEST_SECRET

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Karate tests...
      - ./karatetest/gradlew test \
          -Dkarate.options="$(echo $TEST_SECRET | jq -r .KARATE_OPTIONS)" \
          -Dkarate.env="$(echo $TEST_SECRET | jq -r .ENV)" \
          -Dtest.apiurl="$(echo $TEST_SECRET | jq -r .APIURL | sed 's/\\//g')" \
          -DconnectTimeout="$(echo $TEST_SECRET | jq -r .CONNECT_TIMEOUT)" \
          -DreadTimeout="$(echo $TEST_SECRET | jq -r .KARATE_READTIMEOUT)" \
          -DretryCount="$(echo $TEST_SECRET | jq -r .KARATE_RETRYCOUNT)" \
          -DretryInterval="$(echo $TEST_SECRET | jq -r .RETRYINTERVAL)" \
          -Dtest.username="$(echo $TEST_SECRET | jq -r .username)" \
          -Dtest.password="$(echo $TEST_SECRET | jq -r .password)" \
          -Dtest.url="$(echo $TEST_SECRET | jq -r .DATAINGEST_SERVER_URL | sed 's/\\//g')" \
          -Dtest.driverClassName="$DRIVERCLASSNAME" \
          -Dtest.bootstrapServers="$(echo $TEST_SECRET | jq -r .KAFKA_SERVER | sed 's/\\//g')" \
          -Dtest.groupId="$(echo $TEST_SECRET | jq -r .GROUPID)" \
          -Dtest.apiusername="$(echo $TEST_SECRET | jq -r .API_USERNAME)" \
          -Dtest.apipassword="$(echo $TEST_SECRET | jq -r .API_PASSWORD)" \
          -Dtest.nbsurl="$(echo $TEST_SECRET | jq -r .NBS_URL | sed 's/\\//g')" \
          -Dtest.wrongapiurl="$(echo $TEST_SECRET | jq -r .WRONGAPIURL | sed 's/\\//g')"

artifacts:
  files:
    - 'karatetest/build/cucumber-html-reports/**/*'
    - 'karatetest/build/karate-reports/**/*'
  base-directory: './'
  discard-paths: no
