version: 0.2

env:
  secrets-manager:
    TEST_SECRET: dev/dataingestionteam/karatetest/secrets

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y jq
      - wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
      - tar -xvf amazon-corretto-17-x64-linux-jdk.tar.gz
      - export JAVA_HOME=$(pwd)/jdk-17.0.0.35
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - cd ./karatetest
      - chmod +x gradlew

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Karate tests...
      - |
        TEST_API_URL=$(echo $TEST_SECRET | jq -r .APIURL)
        TEST_USERNAME=$(echo $TEST_SECRET | jq -r .username)
        TEST_PASSWORD=$(echo $TEST_SECRET | jq -r .password)
        TEST_URL=$(echo $TEST_SECRET | jq -r .DATAINGEST_SERVER_URL)
        TEST_BOOTSTRAP_SERVERS=$(echo $TEST_SECRET | jq -r .KAFKA_SERVER)
        TEST_GROUP_ID=$(echo $TEST_SECRET | jq -r .GROUPID)
        TEST_API_USERNAME=$(echo $TEST_SECRET | jq -r .API_USERNAME)
        TEST_API_PASSWORD=$(echo $TEST_SECRET | jq -r .API_PASSWORD)
        TEST_NBS_URL=$(echo $TEST_SECRET | jq -r .NBS_URL)
        TEST_WRONGAPIURL=$(echo $TEST_SECRET | jq -r .WRONGAPIURL)
        ./gradlew test \
        -Dkarate.options="$KARATE_OPTIONS" \
        -Dkarate.env="$KARATE_ENV" \
        -Dtest.apiurl="$TEST_API_URL" \
        -DconnectTimeout="$CONNECT_TIMEOUT" \
        -DreadTimeout="$READ_TIMEOUT" \
        -DretryCount="$RETRY_COUNT" \
        -DretryInterval="$RETRY_INTERVAL" \
        -Dtest.username="$TEST_USERNAME" \
        -Dtest.password="$TEST_PASSWORD" \
        -Dtest.url="$TEST_URL" \
        -Dtest.driverClassName="$TEST_DRIVER_CLASS_NAME" \
        -Dtest.bootstrapServers="$TEST_BOOTSTRAP_SERVERS" \
        -Dtest.groupId="$TEST_GROUP_ID" \
        -Dtest.apiusername="$TEST_API_USERNAME" \
        -Dtest.apipassword="$TEST_API_PASSWORD" \
        -Dtest.nbsurl="$TEST_NBS_URL" \
        -Dtest.wrongapiurl="$TEST_WRONGAPIURL"
