version: 0.2

env:
  secrets-manager:
    KARATE_OPTIONS: ddd:KARATE_OPTIONS
    KARATE_ENV: env:KARATE_ENV
    TEST_API_URL: <SECRET_NAME>:TEST_API_URL
    CONNECT_TIMEOUT: <SECRET_NAME>:CONNECT_TIMEOUT
    READ_TIMEOUT: <SECRET_NAME>:READ_TIMEOUT
    RETRY_COUNT: <SECRET_NAME>:RETRY_COUNT
    RETRY_INTERVAL: <SECRET_NAME>:RETRY_INTERVAL
    TEST_USERNAME: username:TEST_USERNAME
    TEST_PASSWORD: password:TEST_PASSWORD
    TEST_URL: <SECRET_NAME>:TEST_URL
    TEST_DRIVER_CLASS_NAME: <SECRET_NAME>:TEST_DRIVER_CLASS_NAME
    TEST_BOOTSTRAP_SERVERS: <SECRET_NAME>:TEST_BOOTSTRAP_SERVERS
    TEST_GROUP_ID: <SECRET_NAME>:TEST_GROUP_ID
    TEST_API_USERNAME: <SECRET_NAME>:TEST_API_USERNAME
    TEST_API_PASSWORD: <SECRET_NAME>:TEST_API_PASSWORD
    TEST_NBS_URL: <SECRET_NAME>:TEST_NBS_URL
    TEST_WRONGAPIURL: <SECRET_NAME>:TEST_WRONGAPIURL

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - chmod +x karatetest/gradlew

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Karate tests...
      - |
        ./gradlew test \
        -Dkarate.options="$KARATE_OPTIONS" \
        -Dkarate.env="$KARATE_ENV" \
        -Dtest.apiurl="$TEST_API_URL" \
        -DconnectTimeout="$CONNECT_TIMEOUT" \
        -DreadTimeout="$READ_TIMEOUT" \
        -DretryCount="$RETRY_COUNT" \
        -DretryInterval="$RETRY_INTERVAL" \
        -Dtest.username="$TEST_USERNAME" \
        -Dtest.password="$TEST_PASSWORD" \
        -Dtest.url="$TEST_URL" \
        -Dtest.driverClassName="$TEST_DRIVER_CLASS_NAME" \
        -Dtest.bootstrapServers="$TEST_BOOTSTRAP_SERVERS" \
        -Dtest.groupId="$TEST_GROUP_ID" \
        -Dtest.apiusername="$TEST_API_USERNAME" \
        -Dtest.apipassword="$TEST_API_PASSWORD" \
        -Dtest.nbsurl="$TEST_NBS_URL" \
        -Dtest.wrongapiurl="$TEST_WRONGAPIURL"
      
artifacts:
  type: zip
  files:
    - '**/*'
  base-directory: './karatetest/build/cucumber-html-reports/'
  name: karate-cucumberreports.zip

secondary-artifacts:
  reports:
    base-directory: './karatetest/build/karate-reports/'
    files:
      - '**/*'
    type: zip
    name: karate-karatereports.zip
