version: 0.2

phases:
  install:
    commands:
      - echo "Installing unzip"
      - apt-get -y install unzip
      - echo "Installing SDKMAN"
      - curl -s "https://get.sdkman.io" | bash
      - echo "Initializing SDKMAN"
      - /bin/bash -c "source $HOME/.sdkman/bin/sdkman-init.sh"
      - echo "Installing Gradle"
      - sdk install gradle
      - echo "Installing Java"
      - sdk install java
    runtime-versions:
      java: corretto11
    shell: bash

  pre_build:
    commands:
      - echo "Setting up environment..."
      - cd karatetest
      - chmod +x gradlew
    shell: bash

  build:
    commands:
      - echo "Building and running Karate tests..."
      - export KARATE_OPTIONS=${KARATE_OPTIONS}
      - export KARATE_ENV=${ENV}
      - export TEST_API_URL=${APIURL}
      - export CONNECT_TIMEOUT=${CONNECT_TIMEOUT}
      - export READ_TIMEOUT=${KARATE_READTIMEOUT}
      - export RETRY_COUNT=${KARATE_RETRYCOUNT}
      - export RETRY_INTERVAL=${RETRYINTERVAL}
      - export TEST_USERNAME=${DATAINGEST_DB_USERNAME}
      - export TEST_PASSWORD=${DATAINGEST_DB_PASSWORD}
      - export TEST_URL=${DATAINGEST_SERVER_URL}
      - export TEST_DRIVER_CLASS_NAME=${DRIVERCLASSNAME}
      - export TEST_BOOTSTRAP_SERVERS=${KAFKA_SERVER}
      - export TEST_GROUP_ID=${GROUPID}
      - export TEST_API_USERNAME=${API_USERNAME}
      - export TEST_API_PASSWORD=${API_PASSWORD}
      - export TEST_NBS_URL=${NBS_URL}
      - export TEST_WRONGAPIURL=${WRONGAPIURL}
      - ./gradlew test \
          -Dkarate.options="$KARATE_OPTIONS" \
          -Dkarate.env="$KARATE_ENV" \
          -Dtest.apiurl="$TEST_API_URL" \
          -DconnectTimeout="$CONNECT_TIMEOUT" \
          -DreadTimeout="$READ_TIMEOUT" \
          -DretryCount="$RETRY_COUNT" \
          -DretryInterval="$RETRY_INTERVAL" \
          -Dtest.username="$TEST_USERNAME" \
          -Dtest.password="$TEST_PASSWORD" \
          -Dtest.url="$TEST_URL" \
          -Dtest.driverClassName="$TEST_DRIVER_CLASS_NAME" \
          -Dtest.bootstrapServers="$TEST_BOOTSTRAP_SERVERS" \
          -Dtest.groupId="$TEST_GROUP_ID" \
          -Dtest.apiusername="$TEST_API_USERNAME" \
          -Dtest.apipassword="$TEST_API_PASSWORD" \
          -Dtest.nbsurl="$TEST_NBS_URL" \
          -Dtest.wrongapiurl="$TEST_WRONGAPIURL"
    shell: bash

artifacts:
  files:
    - karatetest/build/cucumber-html-reports/**
    - karatetest/build/karate-reports/**
  discard-paths: yes
  name: karate-report
  retention-days: 1